library(httr)
oauth_endpoints("github")
myapp <- oauth_app("github", "c615b1b731a5b9e4efa8", "5d29da2fb79470032b433c9c97f3b09d8bdb0705")
github_token <- oauth2.0_token(oauth_endpoints("github"), myapp)
gtoken <- config(token = github_token)
req <- with_config(gtoken, GET("https://api.github.com/users/jtleek/repos"))
stop_for_status(req)
sapply(1:30, function(x){content(req)[[x]]$name;content(req)[[x]]$created_at})
download.file('https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06pid.csv', 'q2idaho.csv', method='curl')
acs <- read.csv('q2idaho.csv', header=T)
library(sqldf)
sqldf("select pwgtp1 from acs where AGEP < 50")
con <- url("http://biostat.jhsph.edu/~jleek/contact.html")
htmlcode <- readLines(con)
close(con)
nchar(htmlcode[c(10,20,30,100)])
download.file('https://d396qusza40orc.cloudfront.net/getdata%2Fwksst8110.for', 'wksst8110.for', method='curl')
#library(data.table)
wksst <- read.fwf('wksst8110.for', widths=c(10, 9, 4, 9, 4, 9, 4, 9, 4),skip=4)
sum(wksst$V4)
